services:
  app:
    image: ghcr.io/aymanesaj/app:prod
    container_name: app
    expose:
      - "8080"

  nginx:
    image: ghcr.io/aymanesaj/nginx:prod
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
