name: CI - Build and Push Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase owner
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push app image
        run: |
          docker build -t ghcr.io/${{ env.OWNER_LC }}/app:${GITHUB_SHA} ./app
          docker push ghcr.io/${{ env.OWNER_LC }}/app:${GITHUB_SHA}

          docker tag ghcr.io/${{ env.OWNER_LC }}/app:${GITHUB_SHA} ghcr.io/${{ env.OWNER_LC }}/app:prod
          docker push ghcr.io/${{ env.OWNER_LC }}/app:prod


      - name: Build and push nginx image
        run: |
          docker build -t ghcr.io/${{ env.OWNER_LC }}/nginx:${GITHUB_SHA} ./nginx
          docker push ghcr.io/${{ env.OWNER_LC }}/nginx:${GITHUB_SHA}

          docker tag ghcr.io/${{ env.OWNER_LC }}/nginx:${GITHUB_SHA} ghcr.io/${{ env.OWNER_LC }}/nginx:prod
          docker push ghcr.io/${{ env.OWNER_LC }}/nginx:prod

